language: node_js
node_js:
    - 'lts/*'
    - '14'
    - '12'
    - '10'

# Run the the validate script
script:
    - yarn run validate
    - yarn run build

# Using semantic-release, deploy a new version of the library
# We're running multiple node jobs so running on latest Node
# version
deploy:
    skip_cleanup: true
    provider: script
    script: npx semantic-release
    on:
        node: 'lts/*'
