language: node_js
node_js:
# Removed until v11 bug is resolve see #43
# - "node"
  - "10"
  - "8"
  - "6"

# Run the the validate script
script:
  - yarn run validate
  - yarn run build

# Using semantic-release, deploy a new version of the library
# We're running multiple node jobs so running on latest Node
# version
deploy:
  skip_cleanup: true
  provider: script
  script: npx semantic-release
  on:
    node: "10"
